# -*- coding: utf-8 -*-
"""FIAP DATATHON

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YHLd41QMLp_pNePltSlyueF7QVxLFCNe

#BRONZE
"""

import pandas as pd

file = "/content/BASE DE DADOS PEDE 2024 - DATATHON.xlsx"

df_2022 = pd.read_excel(file, sheet_name="PEDE2022")
df_2023 = pd.read_excel(file, sheet_name="PEDE2023")
df_2024 = pd.read_excel(file, sheet_name="PEDE2024")

df_2022["ANO"] = 2022
df_2023["ANO"] = 2023
df_2024["ANO"] = 2024

print(df_2022.shape)
print(df_2023.shape)
print(df_2024.shape)

"""#SILVER

"""

import pandas as pd
import re

def _clean_col(c: str) -> str:
    c = str(c).strip()
    c = c.replace("\n", " ")
    c = re.sub(r"\s+", " ", c)
    return c

def _dedup_columns(cols):
    seen = {}
    out = []
    for c in cols:
        if c not in seen:
            seen[c] = 1
            out.append(c)
        else:
            seen[c] += 1
            out.append(f"{c}__{seen[c]}")
    return out

def padroniza_df(df: pd.DataFrame, ano: int, manter_historico_inde=False, manter_historico_pedra=False) -> pd.DataFrame:
    df = df.copy()

    df.columns = [_clean_col(c) for c in df.columns]
    df.columns = _dedup_columns(df.columns)

    ren = {
        "RA": "ra",
        "Fase": "fase",
        "Turma": "turma",
        "Nome": "nome",
        "Nome Anonimizado": "nome",
        "Ano nasc": "data_nasc",
        # "Data de Nasc": "data_nasc",
        "Idade 22": "idade",
        "Idade": "idade",
        "Gênero": "genero",
        "Ano ingresso": "ano_ingresso",
        "Instituição de ensino": "instituicao_ensino",
        "Nº Av": "qtde_av",
        "Rec Psicologia": "rec_psicologia",
        "Indicado": "indicado_bolsa",
        "Atingiu PV": "ponto_virada",
        "Matem": "matematica",
        "Mat": "matematica",
        "Portug": "portugues",
        "Por": "portugues",
        "Inglês": "ingles",
        "Ing": "ingles",
        "Fase ideal": "fase_ideal",
        "Fase Ideal": "fase_ideal",
        "Defas": "defasagem",
        "Defasagem": "defasagem",
        "Destaque IEG": "destaque_ieg",
        "Destaque IDA": "destaque_ida",
        "Destaque IPV": "destaque_ipv",
    }
    df = df.rename(columns=ren)

    inde_candidates = [
        f"INDE {ano}",
        f"INDE {str(ano)[-2:]}",
        f"INDE {str(ano)[-2:]}__2",
        f"INDE {ano}__2",
    ]
    inde_col = next((c for c in inde_candidates if c in df.columns), None)
    if inde_col:
        df = df.rename(columns={inde_col: "inde"})

    pedra_candidates = [
        f"Pedra {ano}",
        f"Pedra {str(ano)[-2:]}",
        f"Pedra {str(ano)[-2:]}__2",
        f"Pedra {ano}__2",
    ]
    pedra_col = next((c for c in pedra_candidates if c in df.columns), None)
    if pedra_col:
        df = df.rename(columns={pedra_col: "pedra"})

    for i in range(1, 7):
        c = f"Avaliador{i}"
        if c in df.columns:
            df = df.rename(columns={c: f"avaliador{i}"})

    for i in range(1, 5):
        c = f"Rec Av{i}"
        if c in df.columns:
            df = df.rename(columns={c: f"rec_av{i}"})

    metrics = ["IAA", "IEG", "IPS", "IPP", "IDA", "IPV", "IAN"]
    df = df.rename(columns={m: m.lower() for m in metrics if m in df.columns})

    if not manter_historico_inde:
        drop_inde = [c for c in df.columns if re.fullmatch(r"INDE\s(\d{2}|\d{4})(__\d+)?", c) and c != "inde"]
        df = df.drop(columns=drop_inde, errors="ignore")

    if not manter_historico_pedra:
        drop_pedra = [c for c in df.columns if re.fullmatch(r"Pedra\s\d{2,4}(__\d+)?", c) and c != "pedra"]
        df = df.drop(columns=drop_pedra, errors="ignore")

    df["ano"] = ano
    df.columns = [c.lower() for c in df.columns]

    # normalização textual
    for col in df.select_dtypes(include="object").columns:
        df[col] = df[col].astype(str).str.strip()

    # conversão de colunas numéricas importantes
    colunas_numericas = [
        "idade", "ano_ingresso", "inde", "iaa", "ieg", "ips", "ipp", "ida", "ipv", "ian",
        "matematica", "portugues", "ingles", "qtde_av"
    ]
    for col in colunas_numericas:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    return df

df_2022["IPP"] = None

silver_2022 = padroniza_df(df_2022, 2022)
silver_2023 = padroniza_df(df_2023, 2023)
silver_2024 = padroniza_df(df_2024, 2024)

colunas_comuns = sorted(
    set(silver_2022.columns) &
    set(silver_2023.columns) &
    set(silver_2024.columns)
)

silver_base = pd.concat(
    [
        silver_2022[colunas_comuns],
        silver_2023[colunas_comuns],
        silver_2024[colunas_comuns]
    ],
    ignore_index=True
)

silver_base = silver_base.loc[:, ~silver_base.columns.duplicated()]
silver_base = silver_base.drop_duplicates()

print(silver_base.shape)
silver_base.head()

silver_base.info()

silver_base.columns

"""#GOLD

ANALISANDO MÉTRICAS

IAN → adequação de nível

IDA → desempenho acadêmico

IEG → engajamento nas atividades

IAA → autoavaliação

IPS → psicossocial

IPP → psicopedagógico

IPV → ponto de virada
"""

gold_indicadores_ano = (
    silver_base
    .groupby("ano", dropna=False)[["inde", "ida", "ieg", "iaa", "ips", "ipp","ipv", "ian"]]
    .mean()
    .reset_index()
)

gold_indicadores_ano

cols_usar = [
    "ra",
    "ano",

    "fase",
    "fase_ideal",
    "pedra",
    "genero",
    "idade",
    "ano_ingresso",
    "instituicao_ensino",
    "turma",

    "iaa",
    "ian",
    "ida",
    "ieg",
    "ips",
    "ipp",
    "ipv",
    "inde",

    "matematica",
    "portugues",
    "ingles",
    "qtde_av",

    "defasagem"
]

df_modelo = silver_base[cols_usar].copy()

df_modelo

df_modelo.to_excel("df_modelo.xlsx", index=False)
print("DataFrame df_modelo exportado para 'df_modelo.xlsx'")

"""#ANÁLISES"""



"""Testes para responder as perguntas:

Adequação do nível (IAN): Qual é o perfil geral de defasagem dos alunos (IAN) e como ele evolui ao longo do ano?
"""

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(8,5))

sns.lineplot(
    data=df_modelo,
    x="ano",
    y="ian",
    marker="o",
    linewidth=3
)

plt.xticks([2022, 2023, 2024])
plt.ylim(6,8)

plt.title("Evolução da Adequação de Nível dos Alunos (IAN)")
plt.ylabel("Média do IAN")
plt.xlabel("Ano")

plt.grid(alpha=0.3)

plt.show()

"""Quais combinações de indicadores (IDA + IEG + IPS + IPP) elevam mais a nota global do aluno (INDE)?

Resposta: IDA
"""

import seaborn as sns
import matplotlib.pyplot as plt


corr = df_modelo[["inde","ida","ieg","ips","ipp"]].corr()

plt.figure(figsize=(8,6))
sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    vmin=-1, vmax=1,
    linewidths=0.5,
    fmt=".2f"
)

plt.title("Matriz de Correlação dos Indicadores Educacionais")
plt.show()

"""#MODELO DE MACHINE LEARNING"""

import pandas as pd
import numpy as np
import joblib

from sklearn.model_selection import GroupShuffleSplit, cross_validate
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    f1_score,
    roc_auc_score,
    precision_score,
    recall_score,
    classification_report,
    confusion_matrix
)

df = pd.read_excel("df_modelo.xlsx").copy()

df.columns = [c.strip().lower() for c in df.columns]

df = df.sort_values(["ra", "ano"]).reset_index(drop=True)

df

# Criando o target

df["defasagem_next"] = df.groupby("ra")["defasagem"].shift(-1)
df["ano_next"] = df.groupby("ra")["ano"].shift(-1)

# manter apenas transições válidas de um ano para o outro
df_ml = df[df["ano_next"] == df["ano"] + 1].copy()

# target binário
df_ml["target_risco_defasagem"] = (df_ml["defasagem_next"] < 0).astype(int)

print("Shape base ML:", df_ml.shape)
print("\nDistribuição do target:")
print(df_ml["target_risco_defasagem"].value_counts(dropna=False))
print(df_ml["target_risco_defasagem"].value_counts(normalize=True).round(4))

# FEATURES

# IMPORTANTE:
# não usar "defasagem_next" nem qualquer coluna futura
# e evitar usar "defasagem" atual como feature principal,
# porque isso pode deixar o modelo excessivamente dependente
# do próprio conceito que ele tenta prever.
#
# Também optei por NÃO usar IAN aqui.
# Motivo: IAN é muito próximo da ideia de adequação ao nível,
# então pode funcionar como proxy forte demais da própria defasagem.
# Se quiser, depois testamos uma versão com IAN para comparar.

features_num = [
    "idade",
    "ano_ingresso",
    "iaa",
    "ida",
    "ian",
    "ieg",
    "ips",
    "ipp",
    "ipv",
    "inde",
    "matematica",
    "portugues",
    "ingles",
    "qtde_av",
]

features_cat = [
    "ano",
    "fase",
    "fase_ideal",
    "pedra",
    "genero",
    "instituicao_ensino",
    "turma",
]

features = features_num + features_cat

# manter apenas colunas existentes
features = [c for c in features if c in df_ml.columns]
features_num = [c for c in features_num if c in df_ml.columns]
features_cat = [c for c in features_cat if c in df_ml.columns]

# converter categóricas para string
for c in features_cat:
    df_ml[c] = df_ml[c].astype(str)

X = df_ml[features].copy()
y = df_ml["target_risco_defasagem"].copy()
groups = df_ml["ra"].copy()

# PRÉ-PROCESSAMENTO
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="median")),
                    ("scaler", StandardScaler()),
                ]
            ),
            features_num,
        ),
        (
            "cat",
            Pipeline(
                steps=[
                    ("imputer", SimpleImputer(strategy="most_frequent")),
                    ("onehot", OneHotEncoder(handle_unknown="ignore")),
                ]
            ),
            features_cat,
        ),
    ]
)

# MODELO
# LogisticRegression

model = LogisticRegression(
    max_iter=2000,
    class_weight="balanced",
    random_state=42
)

pipeline = Pipeline(
    steps=[
        ("preprocessor", preprocessor),
        ("model", model),
    ]
)


# VALIDAÇÃO ROBUSTA

# usando GroupShuffleSplit por RA para evitar vazamento entre
# treino e teste do mesmo aluno
gss = GroupShuffleSplit(n_splits=5, test_size=0.25, random_state=42)

cv_scores = cross_validate(
    pipeline,
    X,
    y,
    groups=groups,
    cv=gss,
    scoring=[
        "accuracy",
        "balanced_accuracy",
        "f1",
        "roc_auc",
        "precision",
        "recall",
    ],
    return_train_score=False,
)

print("\nMÉTRICAS MÉDIAS - CROSS VALIDATION")
for metric_name, values in cv_scores.items():
    if metric_name.startswith("test_"):
        print(f"{metric_name}: {values.mean():.4f} ± {values.std():.4f}")

# TREINO FINAL

# separação final em treino/teste também por RA
splitter = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=42)
train_idx, test_idx = next(splitter.split(X, y, groups=groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]

print("\nMÉTRICAS HOLDOUT")
print(f"Accuracy:          {accuracy_score(y_test, y_pred):.4f}")
print(f"Balanced Accuracy: {balanced_accuracy_score(y_test, y_pred):.4f}")
print(f"F1-score:          {f1_score(y_test, y_pred):.4f}")
print(f"Precision:         {precision_score(y_test, y_pred):.4f}")
print(f"Recall:            {recall_score(y_test, y_pred):.4f}")
print(f"ROC AUC:           {roc_auc_score(y_test, y_proba):.4f}")

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nMatriz de Confusão")
print(confusion_matrix(y_test, y_pred))


# EXPORTAÇÃO
# salva pipeline completa: preprocessamento + modelo
joblib.dump(pipeline, "modelo_risco_defasagem.joblib")

# opcional: salvar nomes das features esperadas pelo streamlit
joblib.dump(features, "modelo_risco_defasagem_features.joblib")

print("\nArquivos salvos:")
print("- modelo_risco_defasagem.joblib")
print("- modelo_risco_defasagem_features.joblib")


"""#TESTANDO O JOBLIB (testando defasagem) para elaboração do Streamlit

"""

import pandas as pd
import joblib

modelo = joblib.load("modelo_risco_defasagem.joblib")
features = joblib.load("modelo_risco_defasagem_features.joblib")

"""## EXEMPLO DE ALUNO QUE ESTA DEFASADO"""

entrada = pd.DataFrame([{
    "idade": 14,
    "ano_ingresso": 2022,
    "iaa": 7.5,
    "ian": 6.4,
    "ida": 6.8,
    "ieg": 8.1,
    "ips": 7.0,
    "ipp": 6.5,
    "ipv": 7.2,
    "inde": 7.1,
    "matematica": 6.0,
    "portugues": 7.0,
    "ingles": 6.5,
    "qtde_av": 4,
    "ano": 2024,
    "fase": "Fase 3",
    "fase_ideal": "Fase 4",
    "pedra": "Ágata",
    "genero": "F",
    "instituicao_ensino": "Escola Pública",
    "turma": "3A"
}])

entrada = entrada[features]
proba = modelo.predict_proba(entrada)[0][1]

if proba > 0.6:
    risco = "ALTO"
elif proba > 0.3:
    risco = "MÉDIO"
else:
    risco = "BAIXO"
print(proba)
print(risco)

"""## EXEMPLO DE ALUNO QUE NÃO ESTA DEFASADO"""

pythoentrada = pd.DataFrame([{
    "idade": 14,
    "ano_ingresso": 2022,
    "iaa": 9.5,
    "ian": 9.4,
    "ida": 9.8,
    "ieg": 9.1,
    "ips": 8.5,
    "ipp": 8.2,
    "ipv": 8.8,
    "inde": 9.1,
    "matematica": 8.8,
    "portugues": 8.5,
    "ingles": 8.4,
    "qtde_av": 4,
    "ano": 2024,
    "fase": "Fase 4",
    "fase_ideal": "Fase 4",
    "pedra": "Topázio",
    "genero": "F",
    "instituicao_ensino": "Escola Pública",
    "turma": "4A"
}])

entrada = entrada[features]
proba = modelo.predict_proba(entrada)[0][1]

if proba > 0.6:
    risco = "ALTO"
elif proba > 0.3:
    risco = "MÉDIO"
else:
    risco = "BAIXO"

print(proba)
print(risco)